import streamlit as st
import google.generativeai as genai
import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Configure Gemini API
genai.configure(api_key=os.getenv("GOOGLE_API_KEY"))
model = genai.GenerativeModel("gemini-2.5-flash")

# Streamlit UI
st.title("AI Resume Match Engine")

st.write("Paste a job description to analyze fit.")

# Input box
job_text = st.text_area("Enter Job Description:")

# Button
if st.button("Analyze"):

    if not job_text.strip():
        st.warning("Please enter a job description.")

    else:
        try:
            # Send prompt to AI
            prompt = f"""
            Analyze this job description and provide:
            - A short summary
            - A rough fit score (0-100)
            - Key missing skills
            - Suggestions to improve fit

            JOB DESCRIPTION:
            {job_text}
            """

            response = model.generate_content(prompt)

            # Display results
            st.subheader("Results")

            st.write("### Summary")
            st.write(response.text)

            st.write("### Fit Score")
            st.success("AI Generated")

            st.write("### Fit Reasoning")
            st.write("Generated by AI analysis")

            st.write("### Skills Missing")
            st.warning("Not structured yet")

            st.write("### Suggestions")
            st.write("Improve alignment based on job requirements")

        except Exception as e:
            st.error("Something went wrong. Check API key and try again.")
            st.text(str(e))