from fastapi import FastAPI
from pydantic import BaseModel
import google.generativeai as genai
from dotenv import load_dotenv
import os

# Load API key
load_dotenv()

# Configure Gemini
genai.configure(api_key=os.getenv("GOOGLE_API_KEY"))
model = genai.GenerativeModel("gemini-2.5-flash")

app = FastAPI()

class JobRequest(BaseModel):
    job_text: str

@app.get("/")
def home():
    return {"message": "backend is working ✅"}

@app.post("/analyze-job")
def analyze_job(request: JobRequest):
    job_text = request.job_text

    prompt = f"""
    Summarize this job description and give a simple fit score.

    JOB:
    {job_text}
    """

    response = model.generate_content(prompt)

    return {
        "summary": response.text,
        "fit_score": 80,
        "skills_missing": [],
        "fit_reasoning": "Generated by AI",
        "improvement_suggestions": []
    }
